/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lab01.h"

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
