/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab01.h"

int *
wordcount_100_svc(params *argp, struct svc_req *rqstp) 
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Requisicao para contagem de palavras no arquivo %s\n", argp-> name);
	
	return &result;
}

/*int *add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int result;

	printf("Requisicao de adicao para %d e %d\n", argp->x, argp->y);
	result = argp->x + argp->y;
	return(&result);
} /* fim funcao add remota */

