/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAB01_H_RPCGEN
#define _LAB01_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params {
	char name[100];
};
typedef struct params params;

#define PROG 55555555
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define WORDCOUNT 1
extern  int *wordcount_100(params *, CLIENT *);
extern  FILE *wordcount_100_svc(params *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WORDCOUNT 1
extern  int * wordcount_100();
extern  FILE *wordcount_100_svc();
extern int prog_100_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LAB01_H_RPCGEN */
