/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab01.h"

FILE *wordcount_100_svc(params *argp, struct svc_req *rqstp){
	static FILE *result;

	/*
	 * insert server code here
	 */
		/* Input file path */
	printf("Enter file path: ");
	/* Try to open file */
	fptr = fopen(argp->name, "r");

	/* Exit if file not opened successfully */

	if (fptr == NULL){
		printf("Unable to open file.\n");
		printf("Please check you have read previleges.\n");

		exit(EXIT_FAILURE);
	}
	printf("Requisicao para contagem de palavras no arquivo %s\n", argp->name);
	
	return result;
}

/*int *add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int result;

	printf("Requisicao de adicao para %d e %d\n", argp->x, argp->y);
	result = argp->x + argp->y;
	return(&result);
} /* fim funcao add remota */

